name: Build and Fix README

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.5.3
        with:
          # necessary for github-action-til-autoformat-readme
          fetch-depth: 0

      - name: Autoformat README
        id: autoformat
        uses: isGeekCode/github-action-til-autoformat-readme@1.2.1
        with:
          description: |
            개발자로서 성장하는 하루하루를 기록하기위해 만든 공간입니다.
            
              2단계를 통해 학습, 복습하고 있습니다 ✨
              1단계. GitHub에 메모 ✨
              2단계. 블로그에 정리해서 게시 ✨
          footer: |
            [1]: https://simonwillison.net/2020/Apr/20/self-rewriting-readme/
            [2]: https://github.com/jbranchaud/til
          list_most_recent: 5 # optional, lists most recent TILS below description
          date_format: '2020 Jan 15:04' # optional, must align to https://golang.org/pkg/time/#Time.Format

      # 추가된 부분: Autoformat 작업의 성공 여부에 따라 Fix 작업을 실행합니다.
      - name: Fix Readme Links
        if: steps.autoformat.outcome == 'success'
        run: |
          python fix_readme_links.py
          git config user.name "isgeekcode"
          git config user.email "ptuguitar@gmail.com"
          git add README.md
          git commit -m "Fix README links"
          git push
