name: Trigger Repository A Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_repository_a_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository A Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/OWNER_A/REPO_A/actions/workflows/WORKFLOW_A/dispatches \
            -d '{"ref": "main"}'
