name: Fix README Links

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  fix_links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.5.3

      - name: Run Python Script
        run: |
          python .github/workflows/fix_readme_links.py
          git diff
          git config user.name "isGeekCode"
          git config user.email "ptuguitar@naver.com"
          git add README.md
          git commit -m "Fix README links" -a || exit 0
          git push
