name: Fix README Links

on:
  push:
    branches:
      - main

jobs:
  fix_links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.5.3
        
      # Autoformat 작업 이후 30초 대기
      - name: Wait for 30 seconds
        run: |
          sleep 30

      # 30초 후에 README 파일 다시 조회
      - name: Check out repo again
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      # 원격 저장소의 변경 사항 통합
      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Run Python Script
        run: |
          python .github/workflows/fix_readme_links.py
          git diff
          git config user.name "isGeekCode"
          git config user.email "ptuguitar@naver.com"
          git add README.md
          git commit -m "Fix README links"  -a || exit 0
          git push

